# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false
gems:  [jekyll-paginate]

# Setup
title:            "Gabriel's Page"
tagline:          ''
description:      'Ph.D student at SOKENDAI and Associate Researcher at NAOJ. M.Sc in Astronomy (IAG-USP). Celestial Mechanics, Planetary formation and Chaotic dynamics.'
url:              gabrieltxg.github.io
baseurl:          /

author:
  name:           'Gabriel T. Guimarães'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
