# Dependencies
markdown:         redcarpet
highlighter:      rouge
include:          '_pages'

# Permalinks
permalink:        pretty
relative_permalinks: false
gems:  [jekyll-paginate]

# Setup
title:            "Gabriel T. Guimarães (ガブ・ガボ)"
tagline:          ''
description:      'Ph.D student and Associate Researcher @ SOKENDAI/NAOJ. Celestial Mechanics, Planetary formation, Chaotic dynamics and Jazz.'
url:              gabrieltxg.github.io
baseurl:          /

author:
  name:           'Gabriel T. Guimarães'
  email:          mailto:gabrieltxg@gmail.com

paginate:         5



# custom vars
since:                  2020
google_analytics:       G-6SHFSQN5L4
emailme:                mailto:gabrieltxg@gmail.com
github:
  repo:                 https://github.com/gabrieltxg/gabrieltxg.github.io
version:                May.01.2024
orcid_username:         0000-0003-1890-6356
googlescholar_username: C1Vlz6gAAAAJ
researchgate_username:  gabriel-guimaraes-6
linkedin_username:      gabrieltxg
github_username:        gabrieltxg
share_pdf:              no
share_video:            no


github:
  repo:           https://github.com/poole/hyde
